image: maven:3.9-eclipse-temurin-17

before_script:
  - apt-get update -qq && apt-get install -y -qq make

# TODO: define the stages for this pipeline, and add a job for each one
# other than test below. Each job should run the matching Makefile
# target.
stages:
  -compile
  -test
  -package


compile:
  stage: compile
  script:
    - make compile

test:
  stage: test
  script:
    - make test

package :
  stage: package
  script :
      - make package
  artifacts:
    paths:
      - target/*.jar